# Generated by Django 3.1.3 on 2022-03-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analog',
            name='register_input',
        ),
    ]
